v1.0.0 - initial working release
This was made to fix this error in @bevry's valid-directory package:

```
Error #1:
uncaughtException
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/balupton/Projects/campjs/valid-directory/node_modules/valid-filename/index.js from /Users/balupton/Projects/campjs/valid-directory/edition-es2017/index.js not supported.
Instead change the require of /Users/balupton/Projects/campjs/valid-directory/node_modules/valid-filename/index.js in /Users/balupton/Projects/campjs/valid-directory/edition-es2017/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/balupton/Projects/campjs/valid-directory/edition-es2017/index.js:8:42)
Error: The kept editions [] still did not pass for the required node version [10]
    at updateEngines (file:///Users/balupton/Projects/campjs/boundation/source/versions.js:207:12)
    at async updateRuntime (file:///Users/balupton/Projects/campjs/boundation/source/runtime.js:1094:3)
    at async init (file:///Users/balupton/Projects/campjs/boundation/source/index.js:30:2)
    at async main (file:///Users/balupton/Projects/campjs/boundation/source/bin.js:33:2)
```